# Generated by Django 5.2.5 on 2025-08-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('group_type', models.CharField(choices=[('cell', 'Célula'), ('ministry', 'Ministério'), ('course', 'Curso'), ('group', 'Grupo')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Área de Interesse',
                'verbose_name_plural': 'Áreas de Interesse',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('gender', models.CharField(blank=True, max_length=20, verbose_name='Gênero')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('marital_status', models.CharField(blank=True, max_length=50, verbose_name='Estado Civil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('member_status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('visitor', 'Visitante')], default='visitor', max_length=20, verbose_name='Status do Membro')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Data de Entrada')),
                ('last_attendance', models.DateField(blank=True, null=True, verbose_name='Última Presença')),
                ('event_preference', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('ambos', 'Ambos')], default='presencial', max_length=20, verbose_name='Preferência de Eventos')),
                ('availability_notes', models.TextField(blank=True, verbose_name='Disponibilidade')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Última Atividade')),
                ('engagement_score', models.IntegerField(default=0, verbose_name='Score de Engajamento')),
                ('gifts_aptitudes', models.TextField(blank=True, verbose_name='Dons e Aptidões')),
                ('prayer_requests', models.TextField(blank=True, verbose_name='Pedidos de Oração')),
                ('testimonies', models.TextField(blank=True, verbose_name='Testemunhos')),
                ('inchurch_id', models.CharField(max_length=100, unique=True, verbose_name='ID inChurch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Membro'), ('leader', 'Líder'), ('coordinator', 'Coordenador'), ('volunteer', 'Voluntário')], default='member', max_length=20, verbose_name='Função')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('is_current', models.BooleanField(default=True, verbose_name='Participação Atual')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='members.member')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('event_date', models.DateField(verbose_name='Data do Evento')),
                ('event_type', models.CharField(choices=[('service', 'Culto'), ('cell', 'Célula'), ('course', 'Curso'), ('event', 'Evento Especial')], max_length=20, verbose_name='Tipo de Evento')),
                ('attended', models.BooleanField(default=True, verbose_name='Compareceu')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'unique_together': {('member', 'event_name', 'event_date')},
            },
        ),
        migrations.CreateModel(
            name='MemberInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Nível de Interesse (1-5)')),
                ('interest_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.interestarea')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='members.member')),
            ],
            options={
                'verbose_name': 'Interesse do Membro',
                'verbose_name_plural': 'Interesses dos Membros',
                'unique_together': {('member', 'interest_area')},
            },
        ),
    ]
