# Generated by Django 5.2.5 on 2025-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='available_days',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dias disponíveis'),
        ),
        migrations.AddField(
            model_name='member',
            name='available_times',
            field=models.CharField(blank=True, max_length=200, verbose_name='Horários disponíveis'),
        ),
        migrations.AddField(
            model_name='member',
            name='church_attendance_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Há quanto tempo frequenta a igreja'),
        ),
        migrations.AddField(
            model_name='member',
            name='church_discovery',
            field=models.CharField(blank=True, choices=[('indication', 'Indicação de amigo/familiar'), ('event', 'Evento da igreja'), ('social_media', 'Redes sociais'), ('website', 'Site da igreja'), ('location', 'Localização/vizinhança'), ('other', 'Outro')], max_length=20, verbose_name='Como descobriu a igreja'),
        ),
        migrations.AddField(
            model_name='member',
            name='church_discovery_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Como conheceu a igreja (outro)'),
        ),
        migrations.AddField(
            model_name='member',
            name='community_interests',
            field=models.TextField(blank=True, verbose_name='Interesses na comunidade'),
        ),
        migrations.AddField(
            model_name='member',
            name='contact_preference',
            field=models.CharField(blank=True, choices=[('email', 'E-mail'), ('phone', 'Telefone'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20, verbose_name='Preferência de Contato'),
        ),
        migrations.AddField(
            model_name='member',
            name='faith_challenges',
            field=models.TextField(blank=True, verbose_name='Dificuldades na caminhada cristã'),
        ),
        migrations.AddField(
            model_name='member',
            name='faith_stage',
            field=models.CharField(blank=True, choices=[('beginner', 'Iniciante na fé'), ('growing', 'Caminhando na fé'), ('active', 'Atuante na fé'), ('mature', 'Maduro na fé')], max_length=20, verbose_name='Estágio na fé'),
        ),
        migrations.AddField(
            model_name='member',
            name='group_preferences',
            field=models.TextField(blank=True, verbose_name='Preferências de grupos'),
        ),
        migrations.AddField(
            model_name='member',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding completo'),
        ),
        migrations.AddField(
            model_name='member',
            name='open_to_new_groups',
            field=models.BooleanField(default=True, verbose_name='Aberto a novos grupos'),
        ),
        migrations.AddField(
            model_name='member',
            name='pastoral_care_interest',
            field=models.BooleanField(default=False, verbose_name='Interesse em acompanhamento pastoral'),
        ),
        migrations.AddField(
            model_name='member',
            name='previous_churches',
            field=models.TextField(blank=True, verbose_name='Igrejas anteriores'),
        ),
        migrations.AddField(
            model_name='member',
            name='previous_participation',
            field=models.TextField(blank=True, verbose_name='Participações anteriores'),
        ),
        migrations.AddField(
            model_name='member',
            name='seeking_in_church',
            field=models.TextField(blank=True, verbose_name='O que busca na igreja'),
        ),
        migrations.AddField(
            model_name='member',
            name='volunteer_areas',
            field=models.TextField(blank=True, verbose_name='Áreas de interesse para voluntariado'),
        ),
        migrations.AddField(
            model_name='member',
            name='volunteer_interest',
            field=models.BooleanField(default=False, verbose_name='Interesse em voluntariado'),
        ),
        migrations.AlterField(
            model_name='member',
            name='event_preference',
            field=models.CharField(choices=[('presential', 'Presencial'), ('online', 'Online'), ('both', 'Ambos')], default='presential', max_length=20, verbose_name='Preferência de Eventos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('widowed', 'Viúvo(a)'), ('other', 'Outro')], max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('visitor', 'Visitante'), ('new', 'Novo')], default='visitor', max_length=20, verbose_name='Status do Membro'),
        ),
    ]
